{% set name = "types-dateparser" %}
{% set version = "1.1.4.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-dateparser-{{ version }}.tar.gz
  sha256: 0f76578bbae15c8b8701b5efd94db98a97ce0a27aedfe6f14a531170de6db97d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/dateparser-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for dateparser
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
